---
title: 'Suplementary Code 2: Drawing Publication Plots'
author: "Richard Meitern"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(digits = 2)
options(scipen = 9)
options(knitr.kable.NA="")
```

## Introduction

The aim of this document is to draw publication plots.

```{r}
#cleanup memory
gcstuff <- gc(verbose=FALSE); rm(gcstuff);
```


```{r}
#get last birth adding function
source("./R/last_birth.R")

#simplified twinR summary tables 
source("./R/twinR_summary.R")

#fix twinR compute predictions to do prediction with no lambda  as well
source("./R/twinR_predictions.R")

#simple convenience functions
source("./R/utils.R")
```



## Data import 

```{r}
predDir <- ("./data/predictions/")
eeForm <- "cbind(twin_total,singleton_total)~1+births_total" 
origForm <- "cbind(twin_total,singleton_total)~1+births_total+(1_x_pop)"
dmm_EE_fit <- readRDS(paste0(predDir, eeForm, "dmm_EEdata_fig.rds"))
dmm_orig_fit <- readRDS(paste0(predDir, origForm, "dmm_origdata_fig.rds" ))
dmm_EE_nl_fit <- readRDS(paste0(predDir, eeForm, "dmm_EE_nldata_fig.rds"))
dmm_orig_nl_fit <- readRDS(paste0(predDir, origForm, "dmm_orig_nldata_fig.rds"))
```



```{r}
fig2_EE_plot_data <- dmm_EE_fit$results
fig2_orig_plot_data <- dmm_orig_fit$results
```

```{r}
fig2_EE_plot_data_nl <- dmm_EE_nl_fit$results
fig2_EE_plot_data_nl$births_total <- fig2_EE_plot_data_nl$births_total + 1
fig2_orig_plot_data_nl <- dmm_orig_nl_fit$results
fig2_orig_plot_data_nl$births_total <- fig2_orig_plot_data_nl$births_total + 1
```


## Plots 

```{r}
#some labels
estLab <- "Estonian"
westLab <- "9 other European"
```

```{r}
library(ggplot2)
#some nice colours
bc <- c( "azure3","purple4", "navy", "darkgoldenrod2", "springgreen3", "black")

#use new base theme that displays also grid lines 
source("./R/twinR_theme.R")
```


### Fig 1: Estonian vs TwinR Full Data


```{r}

fig2_ext_orig <- ggplot() +  
  geom_line(data=fig2_EE_plot_data,
            aes(y = estimate,  x=births_total, color=estLab),  size = 1) +
  geom_ribbon(data=fig2_EE_plot_data,
              aes(y = estimate,  x=births_total, ymin = lwr, ymax = upr,
                  color=estLab, fill = estLab),
              alpha = 0.3) + 
  geom_line(data=fig2_orig_plot_data,
            aes(y = estimate,  x=births_total, color=westLab),  size = 1) +
  geom_ribbon(data=fig2_orig_plot_data,
              aes(y = estimate,  x=births_total, ymin = lwr, ymax = upr,
                  fill=westLab),
              alpha = 0.3) +
  ggplot2::scale_x_continuous(breaks = 1:18) + 
  ggplot2::scale_y_continuous(trans = "logit",
                              breaks = seq(0.005, 0.025, by = 0.001)) +
  ggplot2::coord_cartesian() +
  labs(subtitle = "(a) Complete datasets",
       y="Per-birth twinning probability",
       x="Maternal total births")
p2 <- fig2_ext_orig + base_theme(larger=5, legend_pos = c(0.5,0.9)) + scale_color_manual(values=bc) + 
  scale_fill_manual(values=bc) + guides(color="none") + labs(fill = "")

p2 
```



### Fig 2: Estonian vs Others No Last Birth



```{r}
fig2_ext_orig <- ggplot() +  
  geom_line(data=fig2_EE_plot_data_nl,
             aes(y = estimate,  x=births_total, color=estLab),  size = 1) +
  geom_ribbon(data=fig2_EE_plot_data_nl,
              aes(y = estimate, x=births_total, ymin = lwr, ymax = upr,
                  color=estLab, fill = estLab),
              alpha = 0.3) + 
  geom_line(data=fig2_orig_plot_data_nl,
            aes(y = estimate,  x=births_total, color=westLab),  size = 1) +
  geom_ribbon(data=fig2_orig_plot_data_nl,
              aes(y = estimate,  x=births_total, ymin = lwr, ymax = upr,
                  fill=westLab),
              alpha = 0.3) +
  ggplot2::scale_x_continuous(breaks = 1:18, limits = c(1,NA)) + 
  ggplot2::scale_y_continuous(trans = "logit",
                              breaks = seq(0.005, 0.025, by = 0.001)) +
  labs(subtitle = "(b) Without last births",
       y="Per-birth twinning probability",
       x="Maternal total births")
p3 <- fig2_ext_orig + base_theme(larger=5, legend_pos = "none") + scale_color_manual(values=bc) + 
  scale_fill_manual(values=bc) + guides(color="none") + labs(fill = "")

p3 
```
```{r, fig.height=11.7, fig.width=8.3}
p2_mod <- p2
p3_mod <- p3 +theme( axis.title.y = element_blank())
plot_1 <- gridExtra::grid.arrange(p2_mod, p3_mod, ncol=2, nrow=2)
```
```{r}
#export A4 plot
ggplot2::ggsave("./exports/figure_1_mother_level_data_twinnig_prob.pdf",
                plot_1, height=11.7, width=8.3)
ggplot2::ggsave("./exports/figure_1_mother_level_data_twinnig_prob.svg",
                plot_1, height=11.7, width=8.3)
```




```{r}
#END
```

